#
# Makefile for Vendor processors family
#

obj-$(CONFIG_ARCH_SS524V100) += mach_ss524v100.o
obj-$(CONFIG_ARCH_SS522V100) += mach_ss524v100.o
obj-$(CONFIG_ARCH_SS522V101) += mach_ss524v100.o
obj-$(CONFIG_ARCH_SS615V100) += mach_ss615v100.o
obj-$(CONFIG_ARCH_SS812V100) += mach_ss812v100.o
obj-$(CONFIG_ARCH_SS101V200) += mach_ss101v200.o
obj-$(CONFIG_ARCH_SS101V500) += mach_ss101v500.o
obj-$(CONFIG_ARCH_SS101V300) += mach_ss101v300.o
obj-$(CONFIG_ARCH_SS101V600) += mach_ss101v600.o
obj-$(CONFIG_ARCH_SS813V100) += mach_ss813v100.o
obj-$(CONFIG_ARCH_SS312V100) += mach_ss312v100.o
obj-$(CONFIG_ARCH_SS313V100) += mach_ss313v100.o
obj-$(CONFIG_ARCH_SS011V100) += mach_ss313v100.o
obj-$(CONFIG_ARCH_SS012V100) += mach_ss313v100.o
obj-$(CONFIG_ARCH_SS612V100) += mach_ss612v100.o
obj-$(CONFIG_ARCH_SS318V100) += mach_ss318v100.o
obj-$(CONFIG_ARCH_SS918V100) += mach_ss918v100.o
obj-$(CONFIG_ARCH_SS013V100) += mach_ss918v100.o


obj-$(CONFIG_SMP)	+= platsmp.o
